# Generated by Django 3.2.2 on 2023-04-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0002_alter_complaint_assignto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department_name',
            field=models.CharField(choices=[('maths', 'maths'), ('BCA', 'BCA'), ('BCOM', 'BCOM'), ('physcics', 'physics'), ('English', 'English'), ('FoodScience', 'FoodScience')], default='maths', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_of_user',
            field=models.CharField(choices=[('student', 'student'), ('staff', 'staff')], default='student', max_length=50),
        ),
    ]
