# Generated by Django 3.2.2 on 2023-04-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0003_auto_20230423_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='staff_reply',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
