# Generated by Django 3.2.2 on 2023-04-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0004_complaint_staff_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Reply',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
